#!/bin/sh

# You'll need to manually install the following
# command line utilities :
# * csstidy to minify CSS
# * jsmin to minify JS

echo ">>> Minify hook started"

if git diff-index --cached HEAD | grep js/script.js > /dev/null 2>&1
then
    if [ -e "js/script.min.js" ]
    then
        rm js/script.min.js
    fi

    if type jsmin 2>/dev/null >/dev/null
    then
        cat js/libs/jquery-2.0.3.min.js js/libs/jquery.cookie.min.js js/script.js | jsmin > js/script.min.js
    else
        cat js/libs/jquery-2.0.3.min.js js/libs/jquery.cookie.min.js js/script.js > js/script.min.js
    fi
    git add js/script.min.js
    echo -e ">>> JS files minified.\n"
fi

if git diff-index --cached HEAD | grep css/style.css > /dev/null 2>&1
then 
    if [ -e "css/style.min.css" ]
    then
        rm css/style.min.css
    fi

    if type jsmin 2>/dev/null >/dev/null
    then
        csstidy css/style.css css/style.min.css
    else
        cp css/style.css css/style.min.css
    fi
    git add css/style.min.css
    echo -e ">>> CSS files minified.\n"
fi

exit 0
