#!/bin/sh

# This hook handle CSS and JS minification

# ******************************************************************
# You'll need to have java installed on your system to use this hook
# ******************************************************************

# *** Replace these two vars if need to use another YUICOMPRESSOR than provided ***
YUICOMPRESSOR=".hooks/yuicompressor-2.4.8.jar"
# ***

if `git diff-index --cached HEAD | grep js/script.js > /dev/null 2>&1` || ! [ -e "js/script.min.js" ]
then
    echo ">>> Minify hook started"
    if [ -e "js/script.min.js" ]
    then
        rm js/script.min.js
    fi

    cat js/jquery-2.0.3.min.js js/jquery.cookie.min.js js/script.js > js/script.tmp.js
    java -jar $YUICOMPRESSOR -o "js/script.min.js" js/script.tmp.js
    rm js/script.tmp.js

    git add js/script.min.js
    echo -e ">>> JS files minified.\n"
fi

if `git diff-index --cached HEAD | grep css/styles.css > /dev/null 2>&1` || ! [ -e "css/styles.min.css" ]
then 
    echo ">>> Minify hook started"
    if [ -e "css/styles.min.css" ]
    then
        rm css/styles.min.css
    fi

    java -jar $YUICOMPRESSOR css/styles.css -o css/styles.min.css
    git add css/styles.min.css
    echo -e ">>> CSS files minified.\n"
fi

exit 0
